"""Reassemble translated batches in _trans/<lang>_batch_NN.json into
all_prompts_576_<lang>.py, using _en_prompts.json as the canonical tensor
(Domain, Context, Mode, Scale) so only the prompt text is the translation.

Verifies every language has exactly 576 prompts, contiguous indices 0..575.
Run after the translation workflow finishes.
"""
import json, glob, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
EN = json.load(open(os.path.join(ROOT, "_en_prompts.json"), encoding="utf-8"))
N = len(EN)  # 576
LANGS = ["de", "fr", "hi", "sw", "zh", "pt"]

problems = []
for lang in LANGS:
    files = sorted(glob.glob(os.path.join(ROOT, "_trans", f"{lang}_batch_*.json")))
    byi = {}
    for f in files:
        try:
            rows = json.load(open(f, encoding="utf-8"))
        except Exception as e:
            problems.append(f"{lang}: {os.path.basename(f)} not valid JSON ({e})")
            continue
        for r in rows:
            byi[int(r["i"])] = r["text"]
    missing = [i for i in range(N) if i not in byi]
    if missing:
        problems.append(f"{lang}: missing {len(missing)} indices e.g. {missing[:10]}")
        continue
    # build the .py module
    var = f"PROMPTS_576_{lang.upper()}"
    out = [
        f'"""{lang} variant of the full 576 tensor. Same combos as all_prompts_576.py, '
        f'translated to {lang}. Generated by parallel Sonnet agents."""',
        "",
        f"{var} = [",
    ]
    for i, (d, c, m, s, _en) in enumerate(EN):
        txt = byi[i]
        out.append(f"    ({d!r}, {c!r}, {m!r}, {s!r},")
        out.append(f"     {txt!r}),")
    out.append("]")
    path = os.path.join(ROOT, f"all_prompts_576_{lang}.py")
    open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"OK {lang}: wrote {os.path.basename(path)} ({len(byi)} prompts)")

if problems:
    print("\nPROBLEMS:")
    for p in problems:
        print(" -", p)
    sys.exit(1)
print("\nAll languages assembled cleanly.")
